version: '3.4'

networks:
  employeesapp:

services:
  employeesdb:
   container_name: app-db
   image: mcr.microsoft.com/mssql/server:2019-latest
   ports:
    - 8002:1433
   environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=password@12345#
   networks:
    - employeesapp
  employeesapp:
    container_name: employees-app
    image: ${DOCKER_REGISTRY-}employeesapp
    build:
      context: .
      dockerfile: EmployeesApp/Dockerfile
    ports:
     - 8001:80
    depends_on:
     - employeesdb
    environment:
     - DB_HOST=employeesdb
     - DB_NAME=EmployeesApp
     - DB_MSSQL_SA_PASSWORD=password@12345#
    networks:
     - employeesapp
   
    
